/**
 * Insight Repository Interface
 * Defines the contract for AI insight data access
 */

import type {
  Insight,
  CallAnalysis,
  InsightFilters,
  InsightStats,
  InsightType,
  SentimentScore,
  QueryParams,
  PaginatedResult,
} from '$lib/domain';
import type { RepositoryOptions } from './types';

// =============================================================================
// Insight Query Parameters
// =============================================================================

/**
 * Extended query parameters for insight queries
 */
export interface InsightQueryParams extends QueryParams {
  filters?: InsightFilters;
}

// =============================================================================
// Insight Repository Interface
// =============================================================================

/**
 * Insight Repository Interface
 * Provides data access operations for AI Insight entities
 * 
 * Note: Insights are typically read-only - they are generated by the AI system
 */
export interface IInsightRepository {
  // =========================================================================
  // Query Operations
  // =========================================================================

  /**
   * Find all insights matching the query parameters
   */
  findAll(params: InsightQueryParams, options?: RepositoryOptions): Promise<PaginatedResult<Insight>>;

  /**
   * Find a single insight by ID
   */
  findById(id: string, options?: RepositoryOptions): Promise<Insight | null>;

  /**
   * Find insights for a specific call
   */
  findByCallLogId(callLogId: string, options?: RepositoryOptions): Promise<Insight[]>;

  /**
   * Find insights for a specific agent
   */
  findByAgentId(agentId: string, params: InsightQueryParams, options?: RepositoryOptions): Promise<PaginatedResult<Insight>>;

  // =========================================================================
  // Call Analysis Operations
  // =========================================================================

  /**
   * Get full call analysis for a call
   */
  getCallAnalysis(callLogId: string): Promise<CallAnalysis | null>;

  /**
   * Search transcripts
   */
  searchTranscripts(searchTerm: string, params: InsightQueryParams): Promise<PaginatedResult<Insight>>;

  // =========================================================================
  // Statistics Operations
  // =========================================================================

  /**
   * Get insight statistics for a date range
   */
  getStats(fromDate: string, toDate: string): Promise<InsightStats>;

  /**
   * Get sentiment distribution for a date range
   */
  getSentimentDistribution(fromDate: string, toDate: string): Promise<Map<SentimentScore, number>>;

  /**
   * Get insight count by type
   */
  getCountByType(fromDate: string, toDate: string): Promise<Map<InsightType, number>>;

  /**
   * Get top topics for a date range
   */
  getTopTopics(fromDate: string, toDate: string, limit?: number): Promise<Array<{ name: string; count: number }>>;

  // =========================================================================
  // Agent Performance
  // =========================================================================

  /**
   * Get agent performance metrics
   */
  getAgentMetrics(agentId: string, fromDate: string, toDate: string): Promise<{
    averageSentiment: number;
    callsAnalyzed: number;
    coachingSuggestionsCount: number;
    topStrengths: string[];
    areasForImprovement: string[];
  }>;

  // =========================================================================
  // Filter View Operations
  // =========================================================================

  /**
   * Get filter views for current user
   */
  getFilterViews(): Promise<FilterView[]>;

  /**
   * Save a filter view (create or update)
   */
  saveFilterView(view: SaveFilterViewInput): Promise<{ id: string }>;

  /**
   * Delete a filter view
   */
  deleteFilterView(viewId: string): Promise<void>;

  // =========================================================================
  // Advanced Search Operations
  // =========================================================================

  /**
   * Search AI insights with complex filters
   */
  searchAIInsights(filters: AIInsightSearchFilters): Promise<AIInsightSearchResult>;
}

/**
 * Filter view for saved searches
 */
export interface FilterView {
  id: string;
  name: string;
  columns: string[];
  filters: Record<string, unknown>;
  isDefault: boolean;
  createdDate: string;
  isOwner: boolean;
}

/**
 * Input for saving a filter view
 */
export interface SaveFilterViewInput {
  id?: string;
  name: string;
  columns: string[];
  filters: Record<string, unknown>;
  isDefault: boolean;
}

/**
 * Filters for AI insight search
 */
export interface AIInsightSearchFilters {
  query?: string;
  startDate?: string;
  endDate?: string;
  sentiment?: 'positive' | 'neutral' | 'negative';
  agentId?: string;
  groupId?: string;
  limit?: number;
  offset?: number;
}

/**
 * AI insight search result item
 */
export interface AIInsightSearchItem {
  id: string;
  name: string;
  uuid: string;
  phoneNumber: string;
  direction: string;
  duration: number;
  timestamp: string;
  summary: string;
  sentiment: 'positive' | 'neutral' | 'negative';
  sentimentScore: number;
  agentName: string;
  groupName: string;
  status: string;
}

/**
 * AI insight search result
 */
export interface AIInsightSearchResult {
  results: AIInsightSearchItem[];
  total: number;
}
